### ISSUE TITLE
linux problem?

### ISSUE THREAD

**Issue by hansbak** [app-appplayer/flutter_mcp#2]
when trying iwth linux i get:
The flutter_mcp package requires native Linux libraries. You need to install them:

sudo apt-get install -y libnotify-dev libsecret-1-dev libappindicator3-dev
[sudo] password for hans:                                                  
Reading package lists... Done                                              
Building dependency tree... Done                                           
Reading state information... Done                                          
libsecret-1-dev is already the newest version (0.20.5-2).                  
Some packages could not be installed. This may mean that you have          
requested an impossible situation or if you are using the unstable         
distribution that some required packages have not yet been created         
or been moved out of Incoming.                                             
The following information may help to resolve the situation:               
                                                                           
The following packages have unmet dependencies:                            
 libayatana-appindicator3-1 : Conflicts: libappindicator3-1                
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused 
by held packages.                                                          
There's a conflict with appindicator. Let's try the ayatana version which is the modern replacement:

sudo apt-get install -y libnotify-dev libayatana-appindicator3-dev
The libraries are installed but the CMakeLists.txt expects appindicator3-0.1 instead of ayatana-appindicator3-0.1. This is a bug in the flutter_mcp package.

can you help?

**Comment by jsha21** [comment]
Thank you for reporting this issue. This has been fixed in version 1.0.5. The CMakeLists.txt now checks for both the modern ayatana-appindicator3 and the legacy appindicator3:

pkg_check_modules(APPINDICATOR ayatana-appindicator3-0.1)
if(NOT APPINDICATOR_FOUND)
  pkg_check_modules(APPINDICATOR REQUIRED appindicator3-0.1)
endif()
To resolve:
Update to flutter_mcp 1.0.5:

dependencies:
  flutter_mcp: ^1.0.5
Install the ayatana version (which you already did):

sudo apt-get install -y libnotify-dev libsecret-1-dev libayatana-appindicator3-dev
Run flutter clean && flutter pub get and rebuild.
This fix supports both modern Linux distributions (Ubuntu 22.04+, Debian 11+) and older ones.

**Comment by finnvyrn** [comment]
Thank you, but this issue is not fixed, at least on Arch Linux.

Package version: 1.0.6
OS: Arch Linux x86_64
Kernel: Linux 7.0.0-1-cachyos

```
/home/finn/projects/my_app/linux/flutter/ephemeral/.plugin_symlinks/flutter_mcp/linux/flutter_mcp_plugin.cc:8:10: fatal error: 'appindicator3-0.1/libappindicator/app-indicator.h' file not found
Error: Build process failed
#0      throwToolExit (package:flutter_tools/src/base/common.dart:34:3)
#1      _runBuild (package:flutter_tools/src/linux/build_linux.dart:219:5)
<asynchronous suspension>
#2      buildLinux
(package:flutter_tools/src/linux/build_linux.dart:100:5)
<asynchronous suspension>
#3      LinuxDevice.buildForDevice
(package:flutter_tools/src/linux/linux_device.dart:67:5)
<asynchronous suspension>
#4      DesktopDevice.startApp
(package:flutter_tools/src/desktop_device.dart:108:7)
<asynchronous suspension>
#5      FlutterDevice.runCold
(package:flutter_tools/src/resident_runner.dart:572:33)
<asynchronous suspension>
#6      ColdRunner.run (package:flutter_tools/src/run_cold.dart:56:28)
<asynchronous suspension>
#7      RunCommand.runCommand
(package:flutter_tools/src/commands/run.dart:904:26)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1590:27)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:154:19)
<asynchronous suspension>
#10     CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#11     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:496:9)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:154:19)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:431:5)
<asynchronous suspension>
#14     FlutterCommandRunner.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:307:33)
<asynchronous suspension>
#15     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:104:11)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:154:19)
<asynchronous suspension>
#17     main (package:flutter_tools/executable.dart:103:3)
<asynchronous suspension>
```

**Comment by jsha21** [comment]
flutter_mcp 2.0.1 was just published (2026-05-04). The Linux dependency list is being updated — recent Ubuntu/Debian uses `libayatana-appindicator3-dev` instead of `libappindicator3-dev` (they conflict with each other). Could you try:

    sudo apt-get install -y libnotify-dev libsecret-1-dev libayatana-appindicator3-dev

against 2.0.1 and let us know if it resolves on your distro? Thanks for the report.
